from typing import Protocol, List, Dict, Any, Optional

class CombatContext(Protocol):
    @property
    def fleets(self) -> List[Any]: ...
    
    @property
    def all_planets(self) -> List[Any]: ...
    
    @property
    def factions(self) -> Dict[str, Any]: ...
    
    @property
    def turn_counter(self) -> int: ...
    
    @property
    def logger(self) -> Optional[Any]: ...
    
    @property
    def telemetry(self) -> Any: ...
    
    @property
    def strategic_ai(self) -> Any: ...
    
    @property
    def game_config(self) -> Dict[str, Any]: ...
    
    @property
    def faction_reporter(self) -> Any: ...
    
    def update_planet_ownership(self, planet: Any, new_owner: str) -> None: ...
    
    def log_battle_result(self, location: str, winner: str, losers: List[str], 
                         rounds: int, survivors: int) -> None: ...
