graph LR
    Tech_BioTide_Collective_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_BioTide_Collective_Logistics["Logistics (T1)"]
    Tech_BioTide_Collective_Industrial Forging["Industrial Forging (T1)"]
    Tech_BioTide_Collective_Resource Extraction["Resource Extraction (T1)"]
    Tech_BioTide_Collective_Heavy Armor["Heavy Armor (T2)"]
    Tech_BioTide_Collective_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_BioTide_Collective_Flux Navigation["Flux Navigation (T2)"]
    Tech_BioTide_Collective_Mega Construction["Mega Construction (T2)"]
    Tech_BioTide_Collective_Trade Networks["Trade Networks (T2)"]
    Tech_BioTide_Collective_Capital Ships["Capital Ships (T3)"]
    Tech_BioTide_Collective_Titan Integration["Titan Integration (T3)"]
    Tech_BioTide_Collective_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_BioTide_Collective_Ascension Protocol["Ascension Protocol (T3)"]