graph LR
    Tech_Hive_Swarm_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Hive_Swarm_Logistics["Logistics (T1)"]
    Tech_Hive_Swarm_Industrial Forging["Industrial Forging (T1)"]
    Tech_Hive_Swarm_Resource Extraction["Resource Extraction (T1)"]
    Tech_Hive_Swarm_Heavy Armor["Heavy Armor (T2)"]
    Tech_Hive_Swarm_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Hive_Swarm_Warp Navigation["Warp Navigation (T2)"]
    Tech_Hive_Swarm_Mega Construction["Mega Construction (T2)"]
    Tech_Hive_Swarm_Trade Networks["Trade Networks (T2)"]
    Tech_Hive_Swarm_Capital Ships["Capital Ships (T3)"]
    Tech_Hive_Swarm_Titan Integration["Titan Integration (T3)"]
    Tech_Hive_Swarm_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Hive_Swarm_Ascension Protocol["Ascension Protocol (T3)"]
    Tech_Hive_Swarm_Spawning Pool["Construction: Spawning Pool (T1)"]
    Tech_Hive_Swarm_Gestation Chamber["Construction: Gestation Chamber (T2)"]
    Tech_Hive_Swarm_Digestion Pool["Construction: Digestion Pool (T1)"]
    Tech_Hive_Swarm_Synaptic Node["Construction: Synaptic Node (T1)"]
    Tech_Hive_Swarm_Spore Chimney["Construction: Spore Chimney (T1)"]
    Tech_Hive_Swarm_Bio-Ship Anchor["Construction: Bio-Ship Anchor (T3)"]
    Tech_Hive_Swarm_Digestion Nexus["Construction: Digestion Nexus (T3)"]