graph LR
    Tech_Iron_Vanguard_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Iron_Vanguard_Logistics["Logistics (T1)"]
    Tech_Iron_Vanguard_Industrial Forging["Industrial Forging (T1)"]
    Tech_Iron_Vanguard_Resource Extraction["Resource Extraction (T1)"]
    Tech_Iron_Vanguard_Heavy Armor["Heavy Armor (T2)"]
    Tech_Iron_Vanguard_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Iron_Vanguard_Warp Navigation["Warp Navigation (T2)"]
    Tech_Iron_Vanguard_Mega Construction["Mega Construction (T2)"]
    Tech_Iron_Vanguard_Trade Networks["Trade Networks (T2)"]
    Tech_Iron_Vanguard_Capital Ships["Capital Ships (T3)"]
    Tech_Iron_Vanguard_Titan Integration["Titan Integration (T3)"]
    Tech_Iron_Vanguard_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Iron_Vanguard_Ascension Protocol["Ascension Protocol (T3)"]
    Tech_Iron_Vanguard_Drill Yard["Construction: Drill Yard (T1)"]
    Tech_Iron_Vanguard_Heavy Assembly Plant["Construction: Heavy Assembly Plant (T2)"]
    Tech_Iron_Vanguard_Mineral Processor["Construction: Mineral Processor (T1)"]
    Tech_Iron_Vanguard_Design Bureau["Construction: Design Bureau (T1)"]
    Tech_Iron_Vanguard_Ferrocrete Bunker["Construction: Ferrocrete Bunker (T1)"]
    Tech_Iron_Vanguard_Orbital Drydock["Construction: Orbital Drydock (T3)"]
    Tech_Iron_Vanguard_Mega-Foundry["Construction: Mega-Foundry (T3)"]