graph LR
    Tech_Nebula_Drifters_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Nebula_Drifters_Logistics["Logistics (T1)"]
    Tech_Nebula_Drifters_Industrial Forging["Industrial Forging (T1)"]
    Tech_Nebula_Drifters_Resource Extraction["Resource Extraction (T1)"]
    Tech_Nebula_Drifters_Heavy Armor["Heavy Armor (T2)"]
    Tech_Nebula_Drifters_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Nebula_Drifters_Flux Navigation["Flux Navigation (T2)"]
    Tech_Nebula_Drifters_Mega Construction["Mega Construction (T2)"]
    Tech_Nebula_Drifters_Trade Networks["Trade Networks (T2)"]
    Tech_Nebula_Drifters_Capital Ships["Capital Ships (T3)"]
    Tech_Nebula_Drifters_Titan Integration["Titan Integration (T3)"]
    Tech_Nebula_Drifters_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Nebula_Drifters_Ascension Protocol["Ascension Protocol (T3)"]