graph LR
    Tech_Primeval_Sentinels_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Primeval_Sentinels_Logistics["Logistics (T1)"]
    Tech_Primeval_Sentinels_Industrial Forging["Industrial Forging (T1)"]
    Tech_Primeval_Sentinels_Resource Extraction["Resource Extraction (T1)"]
    Tech_Primeval_Sentinels_Heavy Armor["Heavy Armor (T2)"]
    Tech_Primeval_Sentinels_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Primeval_Sentinels_Flux Navigation["Flux Navigation (T2)"]
    Tech_Primeval_Sentinels_Mega Construction["Mega Construction (T2)"]
    Tech_Primeval_Sentinels_Trade Networks["Trade Networks (T2)"]
    Tech_Primeval_Sentinels_Capital Ships["Capital Ships (T3)"]
    Tech_Primeval_Sentinels_Titan Integration["Titan Integration (T3)"]
    Tech_Primeval_Sentinels_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Primeval_Sentinels_Ascension Protocol["Ascension Protocol (T3)"]