graph LR
    Tech_Rift_Daemons_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Rift_Daemons_Logistics["Logistics (T1)"]
    Tech_Rift_Daemons_Industrial Forging["Industrial Forging (T1)"]
    Tech_Rift_Daemons_Resource Extraction["Resource Extraction (T1)"]
    Tech_Rift_Daemons_Heavy Armor["Heavy Armor (T2)"]
    Tech_Rift_Daemons_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Rift_Daemons_Warp Navigation["Warp Navigation (T2)"]
    Tech_Rift_Daemons_Mega Construction["Mega Construction (T2)"]
    Tech_Rift_Daemons_Trade Networks["Trade Networks (T2)"]
    Tech_Rift_Daemons_Capital Ships["Capital Ships (T3)"]
    Tech_Rift_Daemons_Titan Integration["Titan Integration (T3)"]
    Tech_Rift_Daemons_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Rift_Daemons_Ascension Protocol["Ascension Protocol (T3)"]
    Tech_Rift_Daemons_Summoning Circle["Construction: Summoning Circle (T1)"]
    Tech_Rift_Daemons_Warp Forge["Construction: Warp Forge (T2)"]
    Tech_Rift_Daemons_Soul Altar["Construction: Soul Altar (T1)"]
    Tech_Rift_Daemons_Library of Chaos["Construction: Library of Chaos (T1)"]
    Tech_Rift_Daemons_Warp Shroud["Construction: Warp Shroud (T1)"]
    Tech_Rift_Daemons_Dimensional Gate["Construction: Dimensional Gate (T3)"]
    Tech_Rift_Daemons_Reality Tear["Construction: Reality Tear (T4)"]