graph LR
    Tech_Scavenger_Clans_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Scavenger_Clans_Logistics["Logistics (T1)"]
    Tech_Scavenger_Clans_Industrial Forging["Industrial Forging (T1)"]
    Tech_Scavenger_Clans_Resource Extraction["Resource Extraction (T1)"]
    Tech_Scavenger_Clans_Heavy Armor["Heavy Armor (T2)"]
    Tech_Scavenger_Clans_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Scavenger_Clans_Warp Navigation["Warp Navigation (T2)"]
    Tech_Scavenger_Clans_Mega Construction["Mega Construction (T2)"]
    Tech_Scavenger_Clans_Trade Networks["Trade Networks (T2)"]
    Tech_Scavenger_Clans_Capital Ships["Capital Ships (T3)"]
    Tech_Scavenger_Clans_Titan Integration["Titan Integration (T3)"]
    Tech_Scavenger_Clans_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Scavenger_Clans_Ascension Protocol["Ascension Protocol (T3)"]
    Tech_Scavenger_Clans_Fight Pit["Construction: Fight Pit (T1)"]
    Tech_Scavenger_Clans_Mek Shop["Construction: Mek Shop (T2)"]
    Tech_Scavenger_Clans_Loot Pile["Construction: Loot Pile (T1)"]
    Tech_Scavenger_Clans_Tinkerer's Shed["Construction: Tinkerer's Shed (T1)"]
    Tech_Scavenger_Clans_Junk Wall["Construction: Junk Wall (T1)"]
    Tech_Scavenger_Clans_Space Hulk Dock["Construction: Space Hulk Dock (T3)"]
    Tech_Scavenger_Clans_Scrap Heap["Construction: Scrap Heap (T1)"]