graph LR
    Tech_ScrapLord_Marauders_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_ScrapLord_Marauders_Logistics["Logistics (T1)"]
    Tech_ScrapLord_Marauders_Industrial Forging["Industrial Forging (T1)"]
    Tech_ScrapLord_Marauders_Resource Extraction["Resource Extraction (T1)"]
    Tech_ScrapLord_Marauders_Heavy Armor["Heavy Armor (T2)"]
    Tech_ScrapLord_Marauders_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_ScrapLord_Marauders_Flux Navigation["Flux Navigation (T2)"]
    Tech_ScrapLord_Marauders_Mega Construction["Mega Construction (T2)"]
    Tech_ScrapLord_Marauders_Trade Networks["Trade Networks (T2)"]
    Tech_ScrapLord_Marauders_Capital Ships["Capital Ships (T3)"]
    Tech_ScrapLord_Marauders_Titan Integration["Titan Integration (T3)"]
    Tech_ScrapLord_Marauders_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_ScrapLord_Marauders_Ascension Protocol["Ascension Protocol (T3)"]