graph LR
    Tech_Solar_Hegemony_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Solar_Hegemony_Logistics["Logistics (T1)"]
    Tech_Solar_Hegemony_Industrial Forging["Industrial Forging (T1)"]
    Tech_Solar_Hegemony_Resource Extraction["Resource Extraction (T1)"]
    Tech_Solar_Hegemony_Heavy Armor["Heavy Armor (T2)"]
    Tech_Solar_Hegemony_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Solar_Hegemony_Warp Navigation["Warp Navigation (T2)"]
    Tech_Solar_Hegemony_Mega Construction["Mega Construction (T2)"]
    Tech_Solar_Hegemony_Trade Networks["Trade Networks (T2)"]
    Tech_Solar_Hegemony_Capital Ships["Capital Ships (T3)"]
    Tech_Solar_Hegemony_Titan Integration["Titan Integration (T3)"]
    Tech_Solar_Hegemony_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Solar_Hegemony_Ascension Protocol["Ascension Protocol (T3)"]
    Tech_Solar_Hegemony_Exterminatus["Exterminatus (T4)"]
    Tech_Solar_Hegemony_Military Academy["Construction: Military Academy (T1)"]
    Tech_Solar_Hegemony_Arsenals of Sol["Construction: Arsenals of Sol (T2)"]
    Tech_Solar_Hegemony_Trade Hub["Construction: Trade Hub (T1)"]
    Tech_Solar_Hegemony_University["Construction: University (T1)"]
    Tech_Solar_Hegemony_Shield Generator["Construction: Shield Generator (T1)"]
    Tech_Solar_Hegemony_Orbital Shipyard["Construction: Orbital Shipyard (T3)"]
    Tech_Solar_Hegemony_Diplomatic Embassy["Construction: Diplomatic Embassy (T2)"]