graph LR
    Tech_Templars_of_the_Flux_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Templars_of_the_Flux_Logistics["Logistics (T1)"]
    Tech_Templars_of_the_Flux_Industrial Forging["Industrial Forging (T1)"]
    Tech_Templars_of_the_Flux_Resource Extraction["Resource Extraction (T1)"]
    Tech_Templars_of_the_Flux_Heavy Armor["Heavy Armor (T2)"]
    Tech_Templars_of_the_Flux_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Templars_of_the_Flux_Flux Navigation["Flux Navigation (T2)"]
    Tech_Templars_of_the_Flux_Mega Construction["Mega Construction (T2)"]
    Tech_Templars_of_the_Flux_Trade Networks["Trade Networks (T2)"]
    Tech_Templars_of_the_Flux_Capital Ships["Capital Ships (T3)"]
    Tech_Templars_of_the_Flux_Titan Integration["Titan Integration (T3)"]
    Tech_Templars_of_the_Flux_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Templars_of_the_Flux_Ascension Protocol["Ascension Protocol (T3)"]