graph LR
    Tech_VoidSpawn_Entities_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_VoidSpawn_Entities_Logistics["Logistics (T1)"]
    Tech_VoidSpawn_Entities_Industrial Forging["Industrial Forging (T1)"]
    Tech_VoidSpawn_Entities_Resource Extraction["Resource Extraction (T1)"]
    Tech_VoidSpawn_Entities_Heavy Armor["Heavy Armor (T2)"]
    Tech_VoidSpawn_Entities_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_VoidSpawn_Entities_Flux Navigation["Flux Navigation (T2)"]
    Tech_VoidSpawn_Entities_Mega Construction["Mega Construction (T2)"]
    Tech_VoidSpawn_Entities_Trade Networks["Trade Networks (T2)"]
    Tech_VoidSpawn_Entities_Capital Ships["Capital Ships (T3)"]
    Tech_VoidSpawn_Entities_Titan Integration["Titan Integration (T3)"]
    Tech_VoidSpawn_Entities_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_VoidSpawn_Entities_Ascension Protocol["Ascension Protocol (T3)"]