graph LR
    Tech_Void_Corsairs_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Void_Corsairs_Logistics["Logistics (T1)"]
    Tech_Void_Corsairs_Industrial Forging["Industrial Forging (T1)"]
    Tech_Void_Corsairs_Resource Extraction["Resource Extraction (T1)"]
    Tech_Void_Corsairs_Heavy Armor["Heavy Armor (T2)"]
    Tech_Void_Corsairs_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Void_Corsairs_Warp Navigation["Warp Navigation (T2)"]
    Tech_Void_Corsairs_Mega Construction["Mega Construction (T2)"]
    Tech_Void_Corsairs_Trade Networks["Trade Networks (T2)"]
    Tech_Void_Corsairs_Capital Ships["Capital Ships (T3)"]
    Tech_Void_Corsairs_Titan Integration["Titan Integration (T3)"]
    Tech_Void_Corsairs_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Void_Corsairs_Ascension Protocol["Ascension Protocol (T3)"]
    Tech_Void_Corsairs_Training Pit["Construction: Training Pit (T1)"]
    Tech_Void_Corsairs_Chop Shop["Construction: Chop Shop (T2)"]
    Tech_Void_Corsairs_Smuggler's Cove["Construction: Smuggler's Cove (T1)"]
    Tech_Void_Corsairs_Tech Scavenger["Construction: Tech Scavenger (T1)"]
    Tech_Void_Corsairs_Hidden Bunkers["Construction: Hidden Bunkers (T1)"]
    Tech_Void_Corsairs_Asteroid Dock["Construction: Asteroid Dock (T3)"]
    Tech_Void_Corsairs_Raider's Haven["Construction: Raider's Haven (T2)"]