graph LR
    Tech_Zealot_Legions_Basic Doctrine["Basic Doctrine (T1)"]
    Tech_Zealot_Legions_Logistics["Logistics (T1)"]
    Tech_Zealot_Legions_Industrial Forging["Industrial Forging (T1)"]
    Tech_Zealot_Legions_Resource Extraction["Resource Extraction (T1)"]
    Tech_Zealot_Legions_Heavy Armor["Heavy Armor (T2)"]
    Tech_Zealot_Legions_Advanced Ballistics["Advanced Ballistics (T2)"]
    Tech_Zealot_Legions_Warp Navigation["Warp Navigation (T2)"]
    Tech_Zealot_Legions_Mega Construction["Mega Construction (T2)"]
    Tech_Zealot_Legions_Trade Networks["Trade Networks (T2)"]
    Tech_Zealot_Legions_Capital Ships["Capital Ships (T3)"]
    Tech_Zealot_Legions_Titan Integration["Titan Integration (T3)"]
    Tech_Zealot_Legions_Planetary Shielding["Planetary Shielding (T3)"]
    Tech_Zealot_Legions_Ascension Protocol["Ascension Protocol (T3)"]
    Tech_Zealot_Legions_Chapel-Barracks["Construction: Chapel-Barracks (T1)"]
    Tech_Zealot_Legions_Pattern Manufactorum["Construction: Pattern Manufactorum (T2)"]
    Tech_Zealot_Legions_Tithe Hall["Construction: Tithe Hall (T1)"]
    Tech_Zealot_Legions_Scriptorium["Construction: Scriptorium (T1)"]
    Tech_Zealot_Legions_Bastion of Faith["Construction: Bastion of Faith (T1)"]
    Tech_Zealot_Legions_Orbital Cathedral["Construction: Orbital Cathedral (T3)"]
    Tech_Zealot_Legions_Conviction Shrine["Construction: Conviction Shrine (T3)"]