
import os
import datetime
from typing import Dict, List, Any
from universes.base.personality_template import FactionPersonality

class AIPersonalityFileGenerator:
    """
    Generates Python code for ai_personalities.py modules from FactionPersonality objects.
    """
    
    def generate_personality_module(self, universe_name: str, 
                                  personalities: Dict[str, FactionPersonality], 
                                  combat_doctrines: Dict[str, Dict]) -> str:
        """
        Generates the full Python module content.
        """
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Header
        code = f'''# Auto-generated AI Personalities for {universe_name}
# Generation Date: {timestamp}
# This file is automatically generated by the AI Personality Extraction Pipeline.
# Manual edits may be overwritten if "extract-ai" is run again without care.

from typing import Dict, Any
from universes.base.personality_template import FactionPersonality

# --- Combat Doctrines ---
COMBAT_DOCTRINES = {{
'''
        
        # Doctrines
        for name, data in combat_doctrines.items():
            code += f'    "{name}": {{\n'
            for k, v in data.items():
                if isinstance(v, str): code += f'        "{k}": "{v}",\n'
                else: code += f'        "{k}": {v},\n'
            code += '    },\n'
        code += '}\n\n'
        
        # Personalities
        code += '# --- Faction Personalities ---\n'
        code += 'PERSONALITY_DB = {\n'
        
        for f_id, p in personalities.items():
            code += self.generate_personality_dict_entry(f_id, p)
            
        code += '}\n\n'
        
        # Helper Functions
        code += '''
def get_personality(faction_name: str) -> FactionPersonality:
    """Returns the personality for a given faction ID, or default."""
    return PERSONALITY_DB.get(faction_name, PERSONALITY_DB.get("default"))

def get_all_personalities() -> Dict[str, FactionPersonality]:
    """Returns the entire personality database."""
    return PERSONALITY_DB

def get_combat_doctrines() -> Dict[str, Dict[str, Any]]:
    """Returns all defined combat doctrines."""
    return COMBAT_DOCTRINES
'''
        return code

    def generate_combat_doctrines(self, personalities: List[FactionPersonality]) -> Dict[str, Dict]:
        """
        Generates doctrine definitions based on those referenced in personalities.
        """
        # Base/Default Doctrines
        doctrines = {
            "STANDARD": {
                "description": "Balanced approach to combat",
                "offensive_bonus": 1.0,
                "defensive_bonus": 1.0
            },
            "AMBUSH": {
                "description": "Hit and run tactics",
                "offensive_bonus": 1.2,
                "defensive_bonus": 0.8,
                "retreat_chance_mult": 1.5
            },
            "SWARM": {
                "description": "Overwhelming numbers",
                "offensive_bonus": 1.1,
                "defensive_bonus": 0.7,
                "cohesion_penalty": 0.2
            },
            "DEFENSIVE_WALL": {
                "description": "Hold the line",
                "offensive_bonus": 0.8,
                "defensive_bonus": 1.3
            },
            "AGGRESSIVE_ASSAULT": {
                "description": "All-out attack",
                "offensive_bonus": 1.4,
                "defensive_bonus": 0.6
            }
        }
        
        # Add any custom ones referenced (placeholder)
        return doctrines

    def generate_personality_dict_entry(self, faction_id: str, p: FactionPersonality) -> str:
        """
        Converts a single personality object to Python code string.
        """
        code = f'    "{faction_id}": FactionPersonality(\n'
        code += f'        name="{p.name}",\n'
        code += f'        aggression={p.aggression},\n'
        code += f'        expansion_bias={p.expansion_bias},\n'
        code += f'        retreat_threshold={p.retreat_threshold},\n'
        code += f'        cohesiveness={p.cohesiveness},\n'
        code += f'        diplomacy_bonus={p.diplomacy_bonus},\n'
        code += f'        combat_doctrine="{p.combat_doctrine}",\n'
        code += f'        tech_focus="{p.tech_focus}",\n'
        
        if p.quirks:
            code += '        quirks={\n'
            for k, v in p.quirks.items():
                if isinstance(v, str): val_str = f'"{v}"'
                else: val_str = str(v)
                code += f'            "{k}": {val_str},\n'
            code += '        },\n'
            
        if p.fleet_composition_balance:
            code += '        fleet_composition_balance={\n'
            for k, v in p.fleet_composition_balance.items():
                code += f'            "{k}": {v},\n'
            code += '        },\n'
            
        code += '    ),\n'
        return code

    def write_to_file(self, universe_path: str, content: str):
        """Writes the generated code to ai_personalities.py."""
        filepath = os.path.join(universe_path, "ai_personalities.py")
        
        # Backup?
        if os.path.exists(filepath):
            # Maybe rename? But we overwrite usually.
            pass
            
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Generated AI Personalities at {filepath}")
